### ISSUE TITLE
Consider using c137.js

### ISSUE THREAD

**Issue by TJKoury** [reearth/resium#445]
[C137.js](https://www.npmjs.com/package/c137.js) is a es6 single file distro making setup and deployment easier.

See [here](https://github.com/DigitalArsenal/cesium-webpack-example/tree/c137.js) for examples using it with different bundlers/ deployment methods.

**Comment by rot1024** [comment]
It is great. I want to see your C137.js repository on GitHub that exec bundle. And, did you try to use an external option in webpack?

**Comment by TJKoury** [comment]
I’m not sure how `resolve.alias` would help, the current distro works well without any additional options (as you can see by the example repo).

**Comment by rot1024** [comment]
Sorry, but I won't use c137.js in Resium because that is not official. Unofficially publishing the c137.js version of Resium is not a problem. 

In create-react-app env, I tried to set `resolve.alias: { "cesium": "c137.js" }` with craco and stopped using `craco-cesium`, but an error occurred:

![image](https://user-images.githubusercontent.com/3888696/98804298-5879d200-2459-11eb-96bd-df406381a440.png)

**Comment by TJKoury** [comment]
c137.js is es6 only, so it won’t work in CommonJS environments that use
“module”.

No problem though, we are working on creating our own integration libraries
for major frameworks.

**Comment by rot1024** [comment]
I added c137.js example: https://github.com/reearth/resium/tree/main/example/c137.js

**Comment by TJKoury** [comment]
It's open source now, Apache 2.0 licensed:

[Github - c137.js](https://github.com/DigitalArsenal/c137.js)
