### ISSUE TITLE
can't get entity id?

### ISSUE THREAD

**Issue by sstephans** [reearth/resium#462]
When creating an entity using the `<Entity>` component, how can I get the id of the created entity? With vanilla cesiumJS the `viewer.add(entity)` function returns the entity that's been created/added so in that case the id can be accessed. What's the resium way?

**Comment by MrShtrahman** [comment]
Hi, encoutered the same problem some time ago.
My solution was to keep a ref of the `<Viewer />` component (as described in resium's docs) called `viewerRef`, and then the object `viewerRef.current.cesiumElement` had all the ID's of my entities.

*Note*: We're still thinking in my team about the best practice of how to keep this global ref, since many components in the tree with `Viewer` as root are using some raw cesium data/properties... But as a temporary solution, I believe it will do the trick for you

**Comment by rot1024** [comment]
ID is automatically generated with no id specification on Entity component. So we refer it to use ref:

```jsx
export default function Example() {
  const entityRef = useRef(null);
  useEffect(() => {
    const id = entityRef.current?.cesiumElement?.id;

    /* something to do with id */
  }, []);

  return <Viewer><Entity ref={entityRef} /></Viewer>;
}
```
